// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyTracker.Data;

#nullable disable

namespace SkyTracker.Data.Migrations
{
    [DbContext(typeof(SkyTrackerDbContext))]
    [Migration("20230703181859_Seed-MappingTables")]
    partial class SeedMappingTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SkyTracker.Data.Models.Aircraft", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Equipment")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Registration")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("Id");

                    b.ToTable("Aircraft");

                    b.HasData(
                        new
                        {
                            Id = "10594670",
                            Equipment = "B06",
                            Registration = "N206MP"
                        },
                        new
                        {
                            Id = "12610754",
                            Equipment = "R44",
                            Registration = "CGPEV"
                        },
                        new
                        {
                            Id = "10801158",
                            Equipment = "BN2P",
                            Registration = "N409WB"
                        },
                        new
                        {
                            Id = "10658329",
                            Equipment = "C208",
                            Registration = "N269TD"
                        },
                        new
                        {
                            Id = "4735111",
                            Equipment = "DHC6",
                            Registration = "PJWIQ"
                        });
                });

            modelBuilder.Entity("SkyTracker.Data.Models.Airport", b =>
                {
                    b.Property<string>("IATA")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ICAO")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IATA");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            IATA = "GKT"
                        },
                        new
                        {
                            IATA = "YKF"
                        },
                        new
                        {
                            IATA = "YCM"
                        },
                        new
                        {
                            IATA = "BUF"
                        },
                        new
                        {
                            IATA = "YHM"
                        },
                        new
                        {
                            IATA = "IAG"
                        },
                        new
                        {
                            IATA = "BID"
                        },
                        new
                        {
                            IATA = "WST"
                        },
                        new
                        {
                            IATA = "ANC"
                        },
                        new
                        {
                            IATA = "ENA"
                        },
                        new
                        {
                            IATA = "SXM"
                        },
                        new
                        {
                            IATA = "SAB"
                        },
                        new
                        {
                            IATA = "SBH"
                        });
                });

            modelBuilder.Entity("SkyTracker.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SkyTracker.Data.Models.Flight", b =>
                {
                    b.Property<string>("FlightId")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("DepartureId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Equipment")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("FlightNumber")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("RealArrival")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Registration")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("Reserved")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScheduledArrival")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FlightId");

                    b.HasIndex("DepartureId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightId = "679748590",
                            Callsign = "N206MP",
                            DepartureId = "GKT",
                            Equipment = "B06",
                            RealArrival = "TYS",
                            Registration = "N206MP",
                            Reserved = "",
                            ScheduledArrival = "TYS"
                        },
                        new
                        {
                            FlightId = "679750895",
                            Callsign = "N206MP",
                            DepartureId = "GKT",
                            Equipment = "B06",
                            RealArrival = "TYS",
                            Registration = "N206MP",
                            Reserved = "",
                            ScheduledArrival = "TYS"
                        },
                        new
                        {
                            FlightId = "679757090",
                            Callsign = "N206MP",
                            DepartureId = "GKT",
                            Equipment = "B06",
                            RealArrival = "TYS",
                            Registration = "N206MP",
                            Reserved = "",
                            ScheduledArrival = "TYS"
                        },
                        new
                        {
                            FlightId = "679761752",
                            Callsign = "N206MP",
                            DepartureId = "GKT",
                            Equipment = "B06",
                            RealArrival = "TYS",
                            Registration = "N206MP",
                            Reserved = "",
                            ScheduledArrival = "TYS"
                        },
                        new
                        {
                            FlightId = "679765704",
                            Callsign = "N206MP",
                            DepartureId = "GKT",
                            Equipment = "B06",
                            RealArrival = "MOR",
                            Registration = "N206MP",
                            Reserved = "",
                            ScheduledArrival = "MOR"
                        },
                        new
                        {
                            FlightId = "679770174",
                            Callsign = "N206MP",
                            DepartureId = "GKT",
                            Equipment = "B06",
                            RealArrival = "TYS",
                            Registration = "N206MP",
                            Reserved = "",
                            ScheduledArrival = "TYS"
                        },
                        new
                        {
                            FlightId = "679784404",
                            Callsign = "N206MP",
                            DepartureId = "GKT",
                            Equipment = "B06",
                            RealArrival = "TYS",
                            Registration = "N206MP",
                            Reserved = "",
                            ScheduledArrival = "TYS"
                        },
                        new
                        {
                            FlightId = "679790096",
                            Callsign = "N206MP",
                            DepartureId = "GKT",
                            Equipment = "B06",
                            RealArrival = "TYS",
                            Registration = "N206MP",
                            Reserved = "",
                            ScheduledArrival = "TYS"
                        },
                        new
                        {
                            FlightId = "679791496",
                            Callsign = "N206MP",
                            DepartureId = "GKT",
                            Equipment = "B06",
                            RealArrival = "TYS",
                            Registration = "N206MP",
                            Reserved = "",
                            ScheduledArrival = "TYS"
                        },
                        new
                        {
                            FlightId = "679794482",
                            Callsign = "N206MP",
                            DepartureId = "GKT",
                            Equipment = "B06",
                            RealArrival = "TYS",
                            Registration = "N206MP",
                            Reserved = "",
                            ScheduledArrival = "TYS"
                        },
                        new
                        {
                            FlightId = "679796785",
                            Callsign = "N206MP",
                            DepartureId = "GKT",
                            Equipment = "B06",
                            RealArrival = "TYS",
                            Registration = "N206MP",
                            Reserved = "",
                            ScheduledArrival = "TYS"
                        },
                        new
                        {
                            FlightId = "679808241",
                            Callsign = "N206MP",
                            DepartureId = "GKT",
                            Equipment = "B06",
                            RealArrival = "TYS",
                            Registration = "N206MP",
                            Reserved = "",
                            ScheduledArrival = "TYS"
                        },
                        new
                        {
                            FlightId = "679811120",
                            Callsign = "N206MP",
                            DepartureId = "GKT",
                            Equipment = "B06",
                            RealArrival = "TYS",
                            Registration = "N206MP",
                            Reserved = "",
                            ScheduledArrival = "TYS"
                        },
                        new
                        {
                            FlightId = "679812684",
                            Callsign = "N206MP",
                            DepartureId = "GKT",
                            Equipment = "B06",
                            RealArrival = "TYS",
                            Registration = "N206MP",
                            Reserved = "",
                            ScheduledArrival = "TYS"
                        },
                        new
                        {
                            FlightId = "679814796",
                            Callsign = "N206MP",
                            DepartureId = "GKT",
                            Equipment = "B06",
                            RealArrival = "TYS",
                            Registration = "N206MP",
                            Reserved = "",
                            ScheduledArrival = "TYS"
                        },
                        new
                        {
                            FlightId = "679817699",
                            Callsign = "N206MP",
                            DepartureId = "GKT",
                            Equipment = "B06",
                            RealArrival = "TYS",
                            Registration = "N206MP",
                            Reserved = "",
                            ScheduledArrival = "TYS"
                        },
                        new
                        {
                            FlightId = "679819640",
                            Callsign = "N206MP",
                            DepartureId = "GKT",
                            Equipment = "B06",
                            RealArrival = "TYS",
                            Registration = "N206MP",
                            Reserved = "",
                            ScheduledArrival = "TYS"
                        },
                        new
                        {
                            FlightId = "679821595",
                            Callsign = "N206MP",
                            DepartureId = "GKT",
                            Equipment = "B06",
                            RealArrival = "TYS",
                            Registration = "N206MP",
                            Reserved = "",
                            ScheduledArrival = "TYS"
                        },
                        new
                        {
                            FlightId = "679823946",
                            Callsign = "N206MP",
                            DepartureId = "GKT",
                            Equipment = "B06",
                            RealArrival = "TYS",
                            Registration = "N206MP",
                            Reserved = "",
                            ScheduledArrival = "TYS"
                        },
                        new
                        {
                            FlightId = "679826809",
                            Callsign = "N206MP",
                            DepartureId = "GKT",
                            Equipment = "B06",
                            RealArrival = "TYS",
                            Registration = "N206MP",
                            Reserved = "",
                            ScheduledArrival = "TYS"
                        },
                        new
                        {
                            FlightId = "679828515",
                            Callsign = "N206MP",
                            DepartureId = "GKT",
                            Equipment = "B06",
                            RealArrival = "TYS",
                            Registration = "N206MP",
                            Reserved = "",
                            ScheduledArrival = "TYS"
                        },
                        new
                        {
                            FlightId = "679846352",
                            Callsign = "N206MP",
                            DepartureId = "GKT",
                            Equipment = "B06",
                            RealArrival = "TYS",
                            Registration = "N206MP",
                            Reserved = "",
                            ScheduledArrival = "TYS"
                        },
                        new
                        {
                            FlightId = "679851834",
                            Callsign = "N206MP",
                            DepartureId = "GKT",
                            Equipment = "B06",
                            RealArrival = "TYS",
                            Registration = "N206MP",
                            Reserved = "",
                            ScheduledArrival = "TYS"
                        },
                        new
                        {
                            FlightId = "679855207",
                            Callsign = "N206MP",
                            DepartureId = "GKT",
                            Equipment = "B06",
                            RealArrival = "TYS",
                            Registration = "N206MP",
                            Reserved = "",
                            ScheduledArrival = "TYS"
                        },
                        new
                        {
                            FlightId = "679707362",
                            Callsign = "CGPEV",
                            DepartureId = "YKF",
                            Equipment = "R44",
                            RealArrival = "YCM",
                            Registration = "CGPEV",
                            Reserved = "",
                            ScheduledArrival = "YCM"
                        },
                        new
                        {
                            FlightId = "679713624",
                            Callsign = "CGPEV",
                            DepartureId = "YCM",
                            Equipment = "R44",
                            RealArrival = "BUF",
                            Registration = "CGPEV",
                            Reserved = "",
                            ScheduledArrival = "BUF"
                        },
                        new
                        {
                            FlightId = "679719352",
                            Callsign = "CGPEV",
                            DepartureId = "BUF",
                            Equipment = "R44",
                            RealArrival = "YHM",
                            Registration = "CGPEV",
                            Reserved = "",
                            ScheduledArrival = "YHM"
                        },
                        new
                        {
                            FlightId = "679726997",
                            Callsign = "CGPEV",
                            DepartureId = "YHM",
                            Equipment = "R44",
                            RealArrival = "YCM",
                            Registration = "CGPEV",
                            Reserved = "",
                            ScheduledArrival = "YCM"
                        },
                        new
                        {
                            FlightId = "679733154",
                            Callsign = "CGPEV",
                            DepartureId = "YCM",
                            Equipment = "R44",
                            RealArrival = "IAG",
                            Registration = "CGPEV",
                            Reserved = "",
                            ScheduledArrival = "IAG"
                        },
                        new
                        {
                            FlightId = "679739359",
                            Callsign = "CGPEV",
                            DepartureId = "IAG",
                            Equipment = "R44",
                            RealArrival = "YHM",
                            Registration = "CGPEV",
                            Reserved = "",
                            ScheduledArrival = "YHM"
                        },
                        new
                        {
                            FlightId = "679747520",
                            Callsign = "CGPEV",
                            DepartureId = "YHM",
                            Equipment = "R44",
                            RealArrival = "YCM",
                            Registration = "CGPEV",
                            Reserved = "",
                            ScheduledArrival = "YCM"
                        },
                        new
                        {
                            FlightId = "679753739",
                            Callsign = "CGPEV",
                            DepartureId = "YCM",
                            Equipment = "R44",
                            RealArrival = "IAG",
                            Registration = "CGPEV",
                            Reserved = "",
                            ScheduledArrival = "IAG"
                        },
                        new
                        {
                            FlightId = "679764400",
                            Callsign = "CGPEV",
                            DepartureId = "IAG",
                            Equipment = "R44",
                            RealArrival = "YHM",
                            Registration = "CGPEV",
                            Reserved = "",
                            ScheduledArrival = "YHM"
                        },
                        new
                        {
                            FlightId = "679774436",
                            Callsign = "CGPEV",
                            DepartureId = "YHM",
                            Equipment = "R44",
                            RealArrival = "YCM",
                            Registration = "CGPEV",
                            Reserved = "",
                            ScheduledArrival = "YCM"
                        },
                        new
                        {
                            FlightId = "679780795",
                            Callsign = "CGPEV",
                            DepartureId = "YCM",
                            Equipment = "R44",
                            RealArrival = "IAG",
                            Registration = "CGPEV",
                            Reserved = "",
                            ScheduledArrival = "IAG"
                        },
                        new
                        {
                            FlightId = "679791388",
                            Callsign = "CGPEV",
                            DepartureId = "IAG",
                            Equipment = "R44",
                            RealArrival = "YHM",
                            Registration = "CGPEV",
                            Reserved = "",
                            ScheduledArrival = "YHM"
                        },
                        new
                        {
                            FlightId = "679802343",
                            Callsign = "CGPEV",
                            DepartureId = "YHM",
                            Equipment = "R44",
                            RealArrival = "YCM",
                            Registration = "CGPEV",
                            Reserved = "",
                            ScheduledArrival = "YCM"
                        },
                        new
                        {
                            FlightId = "679809739",
                            Callsign = "CGPEV",
                            DepartureId = "YCM",
                            Equipment = "R44",
                            RealArrival = "BUF",
                            Registration = "CGPEV",
                            Reserved = "",
                            ScheduledArrival = "BUF"
                        },
                        new
                        {
                            FlightId = "679818719",
                            Callsign = "CGPEV",
                            DepartureId = "BUF",
                            Equipment = "R44",
                            RealArrival = "YHM",
                            Registration = "CGPEV",
                            Reserved = "",
                            ScheduledArrival = "YHM"
                        },
                        new
                        {
                            FlightId = "679831846",
                            Callsign = "CGPEV",
                            DepartureId = "YHM",
                            Equipment = "R44",
                            RealArrival = "YCM",
                            Registration = "CGPEV",
                            Reserved = "",
                            ScheduledArrival = "YCM"
                        },
                        new
                        {
                            FlightId = "679837628",
                            Callsign = "CGPEV",
                            DepartureId = "YCM",
                            Equipment = "R44",
                            RealArrival = "BUF",
                            Registration = "CGPEV",
                            Reserved = "",
                            ScheduledArrival = "BUF"
                        },
                        new
                        {
                            FlightId = "679844139",
                            Callsign = "CGPEV",
                            DepartureId = "BUF",
                            Equipment = "R44",
                            RealArrival = "YHM",
                            Registration = "CGPEV",
                            Reserved = "",
                            ScheduledArrival = "YHM"
                        },
                        new
                        {
                            FlightId = "679850961",
                            Callsign = "CGPEV",
                            DepartureId = "YHM",
                            Equipment = "R44",
                            RealArrival = "YCM",
                            Registration = "CGPEV",
                            Reserved = "",
                            ScheduledArrival = "YCM"
                        },
                        new
                        {
                            FlightId = "679856747",
                            Callsign = "CGPEV",
                            DepartureId = "YCM",
                            Equipment = "R44",
                            RealArrival = "BUF",
                            Registration = "CGPEV",
                            Reserved = "",
                            ScheduledArrival = "BUF"
                        },
                        new
                        {
                            FlightId = "679863999",
                            Callsign = "CGPEV",
                            DepartureId = "BUF",
                            Equipment = "R44",
                            RealArrival = "YHM",
                            Registration = "CGPEV",
                            Reserved = "",
                            ScheduledArrival = "YHM"
                        },
                        new
                        {
                            FlightId = "679614404",
                            Callsign = "N409WB",
                            DepartureId = "BID",
                            Equipment = "BN2P",
                            RealArrival = "WST",
                            Registration = "N409WB",
                            Reserved = "",
                            ScheduledArrival = "WST"
                        },
                        new
                        {
                            FlightId = "679727922",
                            Callsign = "N409WB",
                            DepartureId = "WST",
                            Equipment = "BN2P",
                            RealArrival = "BID",
                            Registration = "N409WB",
                            Reserved = "",
                            ScheduledArrival = "BID"
                        },
                        new
                        {
                            FlightId = "679734609",
                            Callsign = "N409WB",
                            DepartureId = "BID",
                            Equipment = "BN2P",
                            RealArrival = "WST",
                            Registration = "N409WB",
                            Reserved = "",
                            ScheduledArrival = "WST"
                        },
                        new
                        {
                            FlightId = "679740984",
                            Callsign = "N409WB",
                            DepartureId = "WST",
                            Equipment = "BN2P",
                            RealArrival = "BID",
                            Registration = "N409WB",
                            Reserved = "",
                            ScheduledArrival = "BID"
                        },
                        new
                        {
                            FlightId = "679747205",
                            Callsign = "N409WB",
                            DepartureId = "BID",
                            Equipment = "BN2P",
                            RealArrival = "WST",
                            Registration = "N409WB",
                            Reserved = "",
                            ScheduledArrival = "WST"
                        },
                        new
                        {
                            FlightId = "679758316",
                            Callsign = "N409WB",
                            DepartureId = "WST",
                            Equipment = "BN2P",
                            RealArrival = "BID",
                            Registration = "N409WB",
                            Reserved = "",
                            ScheduledArrival = "BID"
                        },
                        new
                        {
                            FlightId = "679765495",
                            Callsign = "N409WB",
                            DepartureId = "BID",
                            Equipment = "BN2P",
                            RealArrival = "WST",
                            Registration = "N409WB",
                            Reserved = "",
                            ScheduledArrival = "WST"
                        },
                        new
                        {
                            FlightId = "679771458",
                            Callsign = "N409WB",
                            DepartureId = "WST",
                            Equipment = "BN2P",
                            RealArrival = "BID",
                            Registration = "N409WB",
                            Reserved = "",
                            ScheduledArrival = "BID"
                        },
                        new
                        {
                            FlightId = "679777572",
                            Callsign = "N409WB",
                            DepartureId = "BID",
                            Equipment = "BN2P",
                            RealArrival = "WST",
                            Registration = "N409WB",
                            Reserved = "",
                            ScheduledArrival = "WST"
                        },
                        new
                        {
                            FlightId = "679784563",
                            Callsign = "N409WB",
                            DepartureId = "WST",
                            Equipment = "BN2P",
                            RealArrival = "BID",
                            Registration = "N409WB",
                            Reserved = "",
                            ScheduledArrival = "BID"
                        },
                        new
                        {
                            FlightId = "679790845",
                            Callsign = "N409WB",
                            DepartureId = "BID",
                            Equipment = "BN2P",
                            RealArrival = "WST",
                            Registration = "N409WB",
                            Reserved = "",
                            ScheduledArrival = "WST"
                        },
                        new
                        {
                            FlightId = "679797902",
                            Callsign = "N409WB",
                            DepartureId = "WST",
                            Equipment = "BN2P",
                            RealArrival = "BID",
                            Registration = "N409WB",
                            Reserved = "",
                            ScheduledArrival = "BID"
                        },
                        new
                        {
                            FlightId = "679804347",
                            Callsign = "N409WB",
                            DepartureId = "BID",
                            Equipment = "BN2P",
                            RealArrival = "WST",
                            Registration = "N409WB",
                            Reserved = "",
                            ScheduledArrival = "WST"
                        },
                        new
                        {
                            FlightId = "679816192",
                            Callsign = "N409WB",
                            DepartureId = "BID",
                            Equipment = "BN2P",
                            RealArrival = "WST",
                            Registration = "N409WB",
                            Reserved = "",
                            ScheduledArrival = "WST"
                        },
                        new
                        {
                            FlightId = "679834468",
                            Callsign = "N409WB",
                            DepartureId = "WST",
                            Equipment = "BN2P",
                            RealArrival = "BID",
                            Registration = "N409WB",
                            Reserved = "",
                            ScheduledArrival = "BID"
                        },
                        new
                        {
                            FlightId = "679839081",
                            Callsign = "N409WB",
                            DepartureId = "BID",
                            Equipment = "BN2P",
                            RealArrival = "WST",
                            Registration = "N409WB",
                            Reserved = "",
                            ScheduledArrival = "WST"
                        },
                        new
                        {
                            FlightId = "679842417",
                            Callsign = "N409WB",
                            DepartureId = "WST",
                            Equipment = "BN2P",
                            RealArrival = "BID",
                            Registration = "N409WB",
                            Reserved = "",
                            ScheduledArrival = "BID"
                        },
                        new
                        {
                            FlightId = "679846327",
                            Callsign = "N409WB",
                            DepartureId = "BID",
                            Equipment = "BN2P",
                            RealArrival = "WST",
                            Registration = "N409WB",
                            Reserved = "",
                            ScheduledArrival = "WST"
                        },
                        new
                        {
                            FlightId = "679862566",
                            Callsign = "N409WB",
                            DepartureId = "BID",
                            Equipment = "BN2P",
                            RealArrival = "WST",
                            Registration = "N409WB",
                            Reserved = "",
                            ScheduledArrival = "WST"
                        },
                        new
                        {
                            FlightId = "679635572",
                            Callsign = "N269TD",
                            DepartureId = "ANC",
                            Equipment = "C208",
                            RealArrival = "ENA",
                            Registration = "N269TD",
                            Reserved = "",
                            ScheduledArrival = "ENA"
                        },
                        new
                        {
                            FlightId = "679643668",
                            Callsign = "N269TD",
                            DepartureId = "ENA",
                            Equipment = "C208",
                            RealArrival = "ANC",
                            Registration = "N269TD",
                            Reserved = "",
                            ScheduledArrival = "ANC"
                        },
                        new
                        {
                            FlightId = "679650031",
                            Callsign = "N269TD",
                            DepartureId = "ANC",
                            Equipment = "C208",
                            RealArrival = "ENA",
                            Registration = "N269TD",
                            Reserved = "",
                            ScheduledArrival = "ENA"
                        },
                        new
                        {
                            FlightId = "679657990",
                            Callsign = "N269TD",
                            DepartureId = "ENA",
                            Equipment = "C208",
                            RealArrival = "ANC",
                            Registration = "N269TD",
                            Reserved = "",
                            ScheduledArrival = "ANC"
                        },
                        new
                        {
                            FlightId = "679662640",
                            Callsign = "N269TD",
                            DepartureId = "ANC",
                            Equipment = "C208",
                            RealArrival = "ENA",
                            Registration = "N269TD",
                            Reserved = "",
                            ScheduledArrival = "ENA"
                        },
                        new
                        {
                            FlightId = "679668617",
                            Callsign = "N269TD",
                            DepartureId = "ENA",
                            Equipment = "C208",
                            RealArrival = "ANC",
                            Registration = "N269TD",
                            Reserved = "",
                            ScheduledArrival = "ANC"
                        },
                        new
                        {
                            FlightId = "679671482",
                            Callsign = "N269TD",
                            DepartureId = "ANC",
                            Equipment = "C208",
                            RealArrival = "ENA",
                            Registration = "N269TD",
                            Reserved = "",
                            ScheduledArrival = "ENA"
                        },
                        new
                        {
                            FlightId = "679727537",
                            Callsign = "N269TD",
                            DepartureId = "ENA",
                            Equipment = "C208",
                            RealArrival = "ANC",
                            Registration = "N269TD",
                            Reserved = "",
                            ScheduledArrival = "ANC"
                        },
                        new
                        {
                            FlightId = "679744597",
                            Callsign = "N269TD",
                            DepartureId = "ANC",
                            Equipment = "C208",
                            RealArrival = "ENA",
                            Registration = "N269TD",
                            Reserved = "",
                            ScheduledArrival = "ENA"
                        },
                        new
                        {
                            FlightId = "679757567",
                            Callsign = "N269TD",
                            DepartureId = "ENA",
                            Equipment = "C208",
                            RealArrival = "ANC",
                            Registration = "N269TD",
                            Reserved = "",
                            ScheduledArrival = "ANC"
                        },
                        new
                        {
                            FlightId = "679774768",
                            Callsign = "N269TD",
                            DepartureId = "ANC",
                            Equipment = "C208",
                            RealArrival = "ENA",
                            Registration = "N269TD",
                            Reserved = "",
                            ScheduledArrival = "ENA"
                        },
                        new
                        {
                            FlightId = "679790185",
                            Callsign = "N269TD",
                            DepartureId = "ENA",
                            Equipment = "C208",
                            RealArrival = "ANC",
                            Registration = "N269TD",
                            Reserved = "",
                            ScheduledArrival = "ANC"
                        },
                        new
                        {
                            FlightId = "679803664",
                            Callsign = "N269TD",
                            DepartureId = "ANC",
                            Equipment = "C208",
                            RealArrival = "ENA",
                            Registration = "N269TD",
                            Reserved = "",
                            ScheduledArrival = "ENA"
                        },
                        new
                        {
                            FlightId = "679814645",
                            Callsign = "N269TD",
                            DepartureId = "ENA",
                            Equipment = "C208",
                            RealArrival = "ANC",
                            Registration = "N269TD",
                            Reserved = "",
                            ScheduledArrival = "ANC"
                        },
                        new
                        {
                            FlightId = "679823514",
                            Callsign = "N269TD",
                            DepartureId = "ANC",
                            Equipment = "C208",
                            RealArrival = "ENA",
                            Registration = "N269TD",
                            Reserved = "",
                            ScheduledArrival = "ENA"
                        },
                        new
                        {
                            FlightId = "679835660",
                            Callsign = "N269TD",
                            DepartureId = "ENA",
                            Equipment = "C208",
                            RealArrival = "ANC",
                            Registration = "N269TD",
                            Reserved = "",
                            ScheduledArrival = "ANC"
                        },
                        new
                        {
                            FlightId = "679841780",
                            Callsign = "N269TD",
                            DepartureId = "ANC",
                            Equipment = "C208",
                            RealArrival = "ENA",
                            Registration = "N269TD",
                            Reserved = "",
                            ScheduledArrival = "ENA"
                        },
                        new
                        {
                            FlightId = "679854848",
                            Callsign = "N269TD",
                            DepartureId = "ENA",
                            Equipment = "C208",
                            RealArrival = "ANC",
                            Registration = "N269TD",
                            Reserved = "",
                            ScheduledArrival = "ANC"
                        },
                        new
                        {
                            FlightId = "679861117",
                            Callsign = "N269TD",
                            DepartureId = "ANC",
                            Equipment = "C208",
                            RealArrival = "ENA",
                            Registration = "N269TD",
                            Reserved = "",
                            ScheduledArrival = "ENA"
                        },
                        new
                        {
                            FlightId = "679709505",
                            Callsign = "WIA401",
                            DepartureId = "SXM",
                            Equipment = "DHC6",
                            RealArrival = "SAB",
                            Registration = "PJWIQ",
                            Reserved = "",
                            ScheduledArrival = "SAB"
                        },
                        new
                        {
                            FlightId = "679716540",
                            Callsign = "WIA402",
                            DepartureId = "SAB",
                            Equipment = "DHC6",
                            RealArrival = "SXM",
                            Registration = "PJWIQ",
                            Reserved = "",
                            ScheduledArrival = "SXM"
                        },
                        new
                        {
                            FlightId = "679720729",
                            Callsign = "WIA623",
                            DepartureId = "SXM",
                            Equipment = "DHC6",
                            RealArrival = "SBH",
                            Registration = "PJWIQ",
                            Reserved = "",
                            ScheduledArrival = "SBH"
                        },
                        new
                        {
                            FlightId = "679760166",
                            Callsign = "WIA624",
                            DepartureId = "SBH",
                            Equipment = "DHC6",
                            RealArrival = "SXM",
                            Registration = "PJWIQ",
                            Reserved = "",
                            ScheduledArrival = "SXM"
                        },
                        new
                        {
                            FlightId = "679767637",
                            Callsign = "WIA631",
                            DepartureId = "SXM",
                            Equipment = "DHC6",
                            RealArrival = "SBH",
                            Registration = "PJWIQ",
                            Reserved = "",
                            ScheduledArrival = "SBH"
                        },
                        new
                        {
                            FlightId = "679773916",
                            Callsign = "WIA632",
                            DepartureId = "SBH",
                            Equipment = "DHC6",
                            RealArrival = "SXM",
                            Registration = "PJWIQ",
                            Reserved = "",
                            ScheduledArrival = "SXM"
                        },
                        new
                        {
                            FlightId = "679781850",
                            Callsign = "WIA641",
                            DepartureId = "SXM",
                            Equipment = "DHC6",
                            RealArrival = "SBH",
                            Registration = "PJWIQ",
                            Reserved = "",
                            ScheduledArrival = "SBH"
                        },
                        new
                        {
                            FlightId = "679790844",
                            Callsign = "WIA642",
                            DepartureId = "SBH",
                            Equipment = "DHC6",
                            RealArrival = "SXM",
                            Registration = "PJWIQ",
                            Reserved = "",
                            ScheduledArrival = "SXM"
                        },
                        new
                        {
                            FlightId = "679798112",
                            Callsign = "WIA651",
                            DepartureId = "SXM",
                            Equipment = "DHC6",
                            RealArrival = "SBH",
                            Registration = "PJWIQ",
                            Reserved = "",
                            ScheduledArrival = "SBH"
                        },
                        new
                        {
                            FlightId = "679803953",
                            Callsign = "WIA652",
                            DepartureId = "SBH",
                            Equipment = "DHC6",
                            RealArrival = "SXM",
                            Registration = "PJWIQ",
                            Reserved = "",
                            ScheduledArrival = "SXM"
                        },
                        new
                        {
                            FlightId = "679818403",
                            Callsign = "WIA659",
                            DepartureId = "SXM",
                            Equipment = "DHC6",
                            RealArrival = "SBH",
                            Registration = "PJWIQ",
                            Reserved = "",
                            ScheduledArrival = "SBH"
                        },
                        new
                        {
                            FlightId = "679822399",
                            Callsign = "WIA660",
                            DepartureId = "SBH",
                            Equipment = "DHC6",
                            RealArrival = "SXM",
                            Registration = "PJWIQ",
                            Reserved = "",
                            ScheduledArrival = "SXM"
                        },
                        new
                        {
                            FlightId = "679828409",
                            Callsign = "WIA671",
                            DepartureId = "SXM",
                            Equipment = "DHC6",
                            RealArrival = "SBH",
                            Registration = "PJWIQ",
                            Reserved = "",
                            ScheduledArrival = "SBH"
                        },
                        new
                        {
                            FlightId = "679832266",
                            Callsign = "WIA672",
                            DepartureId = "SBH",
                            Equipment = "DHC6",
                            RealArrival = "SXM",
                            Registration = "PJWIQ",
                            Reserved = "",
                            ScheduledArrival = "SXM"
                        },
                        new
                        {
                            FlightId = "679843338",
                            Callsign = "WIA441",
                            DepartureId = "SXM",
                            Equipment = "DHC6",
                            RealArrival = "SAB",
                            Registration = "PJWIQ",
                            Reserved = "",
                            ScheduledArrival = "SAB"
                        },
                        new
                        {
                            FlightId = "679847956",
                            Callsign = "WIA441",
                            DepartureId = "SAB",
                            Equipment = "DHC6",
                            RealArrival = "SXM",
                            Registration = "PJWIQ",
                            Reserved = "",
                            ScheduledArrival = "SXM"
                        },
                        new
                        {
                            FlightId = "679853082",
                            Callsign = "WIA442",
                            DepartureId = "SXM",
                            Equipment = "DHC6",
                            RealArrival = "EUX",
                            Registration = "PJWIQ",
                            Reserved = "",
                            ScheduledArrival = "EUX"
                        });
                });

            modelBuilder.Entity("SkyTracker.Data.Models.FlightAircraft", b =>
                {
                    b.Property<string>("FlightId")
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("AircraftId")
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("FlightId", "AircraftId");

                    b.HasIndex("AircraftId");

                    b.ToTable("FlightsAircraft");

                    b.HasData(
                        new
                        {
                            FlightId = "679748590",
                            AircraftId = "10594670"
                        },
                        new
                        {
                            FlightId = "679750895",
                            AircraftId = "10594670"
                        },
                        new
                        {
                            FlightId = "679757090",
                            AircraftId = "10594670"
                        },
                        new
                        {
                            FlightId = "679761752",
                            AircraftId = "10594670"
                        },
                        new
                        {
                            FlightId = "679765704",
                            AircraftId = "10594670"
                        },
                        new
                        {
                            FlightId = "679770174",
                            AircraftId = "10594670"
                        },
                        new
                        {
                            FlightId = "679784404",
                            AircraftId = "10594670"
                        },
                        new
                        {
                            FlightId = "679790096",
                            AircraftId = "10594670"
                        },
                        new
                        {
                            FlightId = "679791496",
                            AircraftId = "10594670"
                        },
                        new
                        {
                            FlightId = "679794482",
                            AircraftId = "10594670"
                        },
                        new
                        {
                            FlightId = "679796785",
                            AircraftId = "10594670"
                        },
                        new
                        {
                            FlightId = "679808241",
                            AircraftId = "10594670"
                        },
                        new
                        {
                            FlightId = "679811120",
                            AircraftId = "10594670"
                        },
                        new
                        {
                            FlightId = "679812684",
                            AircraftId = "10594670"
                        },
                        new
                        {
                            FlightId = "679814796",
                            AircraftId = "10594670"
                        },
                        new
                        {
                            FlightId = "679817699",
                            AircraftId = "10594670"
                        },
                        new
                        {
                            FlightId = "679819640",
                            AircraftId = "10594670"
                        },
                        new
                        {
                            FlightId = "679821595",
                            AircraftId = "10594670"
                        },
                        new
                        {
                            FlightId = "679823946",
                            AircraftId = "10594670"
                        },
                        new
                        {
                            FlightId = "679826809",
                            AircraftId = "10594670"
                        },
                        new
                        {
                            FlightId = "679828515",
                            AircraftId = "10594670"
                        },
                        new
                        {
                            FlightId = "679846352",
                            AircraftId = "10594670"
                        },
                        new
                        {
                            FlightId = "679851834",
                            AircraftId = "10594670"
                        },
                        new
                        {
                            FlightId = "679855207",
                            AircraftId = "10594670"
                        },
                        new
                        {
                            FlightId = "679707362",
                            AircraftId = "12610754"
                        },
                        new
                        {
                            FlightId = "679713624",
                            AircraftId = "12610754"
                        },
                        new
                        {
                            FlightId = "679719352",
                            AircraftId = "12610754"
                        },
                        new
                        {
                            FlightId = "679726997",
                            AircraftId = "12610754"
                        },
                        new
                        {
                            FlightId = "679733154",
                            AircraftId = "12610754"
                        },
                        new
                        {
                            FlightId = "679739359",
                            AircraftId = "12610754"
                        },
                        new
                        {
                            FlightId = "679747520",
                            AircraftId = "12610754"
                        },
                        new
                        {
                            FlightId = "679753739",
                            AircraftId = "12610754"
                        },
                        new
                        {
                            FlightId = "679764400",
                            AircraftId = "12610754"
                        },
                        new
                        {
                            FlightId = "679774436",
                            AircraftId = "12610754"
                        },
                        new
                        {
                            FlightId = "679780795",
                            AircraftId = "12610754"
                        },
                        new
                        {
                            FlightId = "679791388",
                            AircraftId = "12610754"
                        },
                        new
                        {
                            FlightId = "679802343",
                            AircraftId = "12610754"
                        },
                        new
                        {
                            FlightId = "679809739",
                            AircraftId = "12610754"
                        },
                        new
                        {
                            FlightId = "679818719",
                            AircraftId = "12610754"
                        },
                        new
                        {
                            FlightId = "679831846",
                            AircraftId = "12610754"
                        },
                        new
                        {
                            FlightId = "679837628",
                            AircraftId = "12610754"
                        },
                        new
                        {
                            FlightId = "679844139",
                            AircraftId = "12610754"
                        },
                        new
                        {
                            FlightId = "679850961",
                            AircraftId = "12610754"
                        },
                        new
                        {
                            FlightId = "679856747",
                            AircraftId = "12610754"
                        },
                        new
                        {
                            FlightId = "679863999",
                            AircraftId = "12610754"
                        },
                        new
                        {
                            FlightId = "679614404",
                            AircraftId = "10801158"
                        },
                        new
                        {
                            FlightId = "679727922",
                            AircraftId = "10801158"
                        },
                        new
                        {
                            FlightId = "679734609",
                            AircraftId = "10801158"
                        },
                        new
                        {
                            FlightId = "679740984",
                            AircraftId = "10801158"
                        },
                        new
                        {
                            FlightId = "679747205",
                            AircraftId = "10801158"
                        },
                        new
                        {
                            FlightId = "679758316",
                            AircraftId = "10801158"
                        },
                        new
                        {
                            FlightId = "679765495",
                            AircraftId = "10801158"
                        },
                        new
                        {
                            FlightId = "679771458",
                            AircraftId = "10801158"
                        },
                        new
                        {
                            FlightId = "679777572",
                            AircraftId = "10801158"
                        },
                        new
                        {
                            FlightId = "679784563",
                            AircraftId = "10801158"
                        },
                        new
                        {
                            FlightId = "679790845",
                            AircraftId = "10801158"
                        },
                        new
                        {
                            FlightId = "679797902",
                            AircraftId = "10801158"
                        },
                        new
                        {
                            FlightId = "679804347",
                            AircraftId = "10801158"
                        },
                        new
                        {
                            FlightId = "679816192",
                            AircraftId = "10801158"
                        },
                        new
                        {
                            FlightId = "679834468",
                            AircraftId = "10801158"
                        },
                        new
                        {
                            FlightId = "679839081",
                            AircraftId = "10801158"
                        },
                        new
                        {
                            FlightId = "679842417",
                            AircraftId = "10801158"
                        },
                        new
                        {
                            FlightId = "679846327",
                            AircraftId = "10801158"
                        },
                        new
                        {
                            FlightId = "679862566",
                            AircraftId = "10801158"
                        },
                        new
                        {
                            FlightId = "679635572",
                            AircraftId = "10658329"
                        },
                        new
                        {
                            FlightId = "679643668",
                            AircraftId = "10658329"
                        },
                        new
                        {
                            FlightId = "679650031",
                            AircraftId = "10658329"
                        },
                        new
                        {
                            FlightId = "679657990",
                            AircraftId = "10658329"
                        },
                        new
                        {
                            FlightId = "679662640",
                            AircraftId = "10658329"
                        },
                        new
                        {
                            FlightId = "679668617",
                            AircraftId = "10658329"
                        },
                        new
                        {
                            FlightId = "679671482",
                            AircraftId = "10658329"
                        },
                        new
                        {
                            FlightId = "679727537",
                            AircraftId = "10658329"
                        },
                        new
                        {
                            FlightId = "679744597",
                            AircraftId = "10658329"
                        },
                        new
                        {
                            FlightId = "679757567",
                            AircraftId = "10658329"
                        },
                        new
                        {
                            FlightId = "679774768",
                            AircraftId = "10658329"
                        },
                        new
                        {
                            FlightId = "679790185",
                            AircraftId = "10658329"
                        },
                        new
                        {
                            FlightId = "679803664",
                            AircraftId = "10658329"
                        },
                        new
                        {
                            FlightId = "679814645",
                            AircraftId = "10658329"
                        },
                        new
                        {
                            FlightId = "679823514",
                            AircraftId = "10658329"
                        },
                        new
                        {
                            FlightId = "679835660",
                            AircraftId = "10658329"
                        },
                        new
                        {
                            FlightId = "679841780",
                            AircraftId = "10658329"
                        },
                        new
                        {
                            FlightId = "679854848",
                            AircraftId = "10658329"
                        },
                        new
                        {
                            FlightId = "679861117",
                            AircraftId = "10658329"
                        },
                        new
                        {
                            FlightId = "679709505",
                            AircraftId = "4735111"
                        },
                        new
                        {
                            FlightId = "679716540",
                            AircraftId = "4735111"
                        },
                        new
                        {
                            FlightId = "679720729",
                            AircraftId = "4735111"
                        },
                        new
                        {
                            FlightId = "679760166",
                            AircraftId = "4735111"
                        },
                        new
                        {
                            FlightId = "679767637",
                            AircraftId = "4735111"
                        },
                        new
                        {
                            FlightId = "679773916",
                            AircraftId = "4735111"
                        },
                        new
                        {
                            FlightId = "679781850",
                            AircraftId = "4735111"
                        },
                        new
                        {
                            FlightId = "679790844",
                            AircraftId = "4735111"
                        },
                        new
                        {
                            FlightId = "679798112",
                            AircraftId = "4735111"
                        },
                        new
                        {
                            FlightId = "679803953",
                            AircraftId = "4735111"
                        },
                        new
                        {
                            FlightId = "679818403",
                            AircraftId = "4735111"
                        },
                        new
                        {
                            FlightId = "679822399",
                            AircraftId = "4735111"
                        },
                        new
                        {
                            FlightId = "679828409",
                            AircraftId = "4735111"
                        },
                        new
                        {
                            FlightId = "679832266",
                            AircraftId = "4735111"
                        },
                        new
                        {
                            FlightId = "679843338",
                            AircraftId = "4735111"
                        },
                        new
                        {
                            FlightId = "679847956",
                            AircraftId = "4735111"
                        },
                        new
                        {
                            FlightId = "679853082",
                            AircraftId = "4735111"
                        });
                });

            modelBuilder.Entity("SkyTracker.Data.Models.HeraldPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occurrence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOccurence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HeraldPosts");
                });

            modelBuilder.Entity("SkyTracker.Data.Models.Runway", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("RunwayDesignatorOne")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RunwayDesignatorTwo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurfaceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Runways");
                });

            modelBuilder.Entity("SkyTracker.Data.Models.RunwayAirport", b =>
                {
                    b.Property<string>("RunwayId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AirportId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RunwayId", "AirportId");

                    b.HasIndex("AirportId");

                    b.ToTable("RunwaysAirports");

                    b.HasData(
                        new
                        {
                            RunwayId = "b9eba418-353c-49fd-b69e-f0ffb38a4d81",
                            AirportId = "GKT"
                        },
                        new
                        {
                            RunwayId = "aa639864-465e-4d50-8baf-b55615bfa3f4",
                            AirportId = "YKF"
                        },
                        new
                        {
                            RunwayId = "aacabf09-804f-4c32-ba81-38db7c476134",
                            AirportId = "YCM"
                        },
                        new
                        {
                            RunwayId = "875682aa-ff3f-4f8e-8e06-3529b271895c",
                            AirportId = "BUF"
                        },
                        new
                        {
                            RunwayId = "bc4a64f8-4bbf-4222-a11d-d938099c32a1",
                            AirportId = "YHM"
                        },
                        new
                        {
                            RunwayId = "6ba984d8-644c-4d42-9909-4c1e76f1bf67",
                            AirportId = "IAG"
                        },
                        new
                        {
                            RunwayId = "b2a93364-116d-419c-999c-492596ecba6f",
                            AirportId = "BID"
                        },
                        new
                        {
                            RunwayId = "1bdefbbc-1ab7-478c-af84-052ac66235b8",
                            AirportId = "WST"
                        },
                        new
                        {
                            RunwayId = "1bdefbbc-1ab7-478c-af84-052ac66235b8",
                            AirportId = "ANC"
                        },
                        new
                        {
                            RunwayId = "2c509f31-28f2-4431-968c-53596d98116c",
                            AirportId = "ENA"
                        },
                        new
                        {
                            RunwayId = "a4247cd5-1475-4771-a703-e79fbb092108",
                            AirportId = "SXM"
                        },
                        new
                        {
                            RunwayId = "2c509f31-28f2-4431-968c-53596d98116c",
                            AirportId = "SAB"
                        },
                        new
                        {
                            RunwayId = "f97199aa-7ddb-4e17-9e6f-24dfc488c3c7",
                            AirportId = "SBH"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SkyTracker.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SkyTracker.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkyTracker.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SkyTracker.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SkyTracker.Data.Models.Flight", b =>
                {
                    b.HasOne("SkyTracker.Data.Models.Airport", "ScheduledDeparture")
                        .WithMany()
                        .HasForeignKey("DepartureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledDeparture");
                });

            modelBuilder.Entity("SkyTracker.Data.Models.FlightAircraft", b =>
                {
                    b.HasOne("SkyTracker.Data.Models.Aircraft", "Aircraft")
                        .WithMany("FlightsAircraft")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkyTracker.Data.Models.Flight", "Flight")
                        .WithMany("FlightsAircraft")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("SkyTracker.Data.Models.RunwayAirport", b =>
                {
                    b.HasOne("SkyTracker.Data.Models.Airport", "Airport")
                        .WithMany("RunwaysAirports")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkyTracker.Data.Models.Runway", "Runway")
                        .WithMany("RunwaysAirports")
                        .HasForeignKey("RunwayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");

                    b.Navigation("Runway");
                });

            modelBuilder.Entity("SkyTracker.Data.Models.Aircraft", b =>
                {
                    b.Navigation("FlightsAircraft");
                });

            modelBuilder.Entity("SkyTracker.Data.Models.Airport", b =>
                {
                    b.Navigation("RunwaysAirports");
                });

            modelBuilder.Entity("SkyTracker.Data.Models.Flight", b =>
                {
                    b.Navigation("FlightsAircraft");
                });

            modelBuilder.Entity("SkyTracker.Data.Models.Runway", b =>
                {
                    b.Navigation("RunwaysAirports");
                });
#pragma warning restore 612, 618
        }
    }
}
